# Generated by Django 3.2 on 2021-11-15 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_amis_render', '0002_auto_20211115_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amisrenderlist',
            name='temp_json_url_name',
        ),
    ]
