# Generated by Django 3.2.8 on 2021-11-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_amis_render', '0003_remove_amisrenderlist_temp_json_url_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmisRenderApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.TextField(blank=True, help_text='文件所在的app的名称', null=True)),
                ('page_count', models.IntegerField(blank=True, help_text='此app中的json文件个数', null=True)),
            ],
            options={
                'verbose_name_plural': 'AMIS-BY-APP',
                'db_table': 'amis_render_app',
                'managed': True,
            },
        ),
    ]
