# Generated by Django 3.2.8 on 2021-11-23 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_amis_render', '0005_auto_20211122_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amisrenderlist',
            name='json_file_url',
            field=models.TextField(blank=True, help_text='static时用于获取json数据的url.一般来说不需要用户填写。temp时无用', null=True),
        ),
    ]
